"use client"

import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { supabase } from '@/lib/supabaseClient'
import { Loader2, Calendar as CalendarIcon, ChevronRight, ChevronLeft, Target, ShieldCheck, CheckCircle2, Lock } from 'lucide-react'

export default function PawgressPlanView({ dogId, onAddVideo }: { dogId: string, onAddVideo: () => void }) {
    const [isLoading, setIsLoading] = useState(true)
    const [aiLog, setAiLog] = useState<any>(null)
    const [selectedDay, setSelectedDay] = useState(1)

    useEffect(() => {
        const fetchPlan = async () => {
            setIsLoading(true)
            // Get the latest completed submission and its feedback log
            const { data: submissionData } = await supabase
                .from('k9_video_submissions')
                .select(`
                    id,
                    status,
                    k9_ai_feedback_logs (
                        raw_json_response
                    )
                `)
                .eq('dog_id', dogId)
                .eq('status', 'analyzed')
                .order('created_at', { ascending: false })
                .limit(1)
                .single()

            if (submissionData && submissionData.k9_ai_feedback_logs && submissionData.k9_ai_feedback_logs.length > 0) {
                setAiLog(submissionData.k9_ai_feedback_logs[0])
            }

            setIsLoading(false)
        }

        fetchPlan()
    }, [dogId])

    if (isLoading) {
        return <div className="flex w-full min-h-[400px] items-center justify-center"><Loader2 className="animate-spin text-[#2D2D2D] w-10 h-10" /></div>
    }

    if (!aiLog) {
        return (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex-1 bg-white rounded-3xl p-12 shadow-sm border border-[#2D2D2D]/5 flex items-center justify-center text-center min-h-[500px]">
                <div className="max-w-md">
                    <div className="w-20 h-20 bg-[#2D2D2D]/5 rounded-2xl flex items-center justify-center mx-auto mb-6 text-[#2D2D2D]/40">
                        <CalendarIcon size={32} />
                    </div>
                    <h3 className="text-2xl font-bold mb-2">No Training Plan Yet</h3>
                    <p className="text-[#2D2D2D]/60 text-sm leading-relaxed mb-8">
                        Your dog's personalized 60-day plan will dynamically generate here once you upload an assessment video for Pawgress AI to analyze.
                    </p>
                    <button onClick={onAddVideo} className="px-6 py-3 bg-[#2D2D2D] text-white font-bold rounded-xl hover:bg-black transition-all text-sm">
                        Upload Video
                    </button>
                </div>
            </motion.div>
        )
    }

    // Parse the JSON
    const planData = aiLog.raw_json_response?.training_plan || []
    const drillsSource = aiLog.raw_json_response?.drills || []

    // Safety fallback if the AI returned a bad schema
    const safePlan = Array.isArray(planData) ? planData : []
    const currentDayData = safePlan.find((d: any) => d.day === selectedDay) || { day: selectedDay, focus: "Rest & Review", drills: [], description: "Take it easy today and reinforce prior learnings." }

    const dayNumber = currentDayData.day

    return (
        <div className="flex flex-col gap-6">
            {/* AI Actionable Feedback */}
            {aiLog.behavior_evaluation && aiLog.behavior_evaluation !== "Initial Baseline Assessment generated from textual profile." && (
                <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-100 rounded-3xl p-6 flex flex-col md:flex-row md:items-center gap-6 shadow-sm">
                    <div className="p-4 bg-white rounded-2xl shadow-sm border border-blue-100 text-blue-600 shrink-0">
                        <Target className="w-8 h-8" />
                    </div>
                    <div>
                        <h4 className="font-black text-gray-900 text-lg tracking-tight mb-2">Pawgress AI Assessment</h4>
                        <p className="text-gray-700 leading-relaxed text-sm max-w-4xl font-medium">
                            {aiLog.behavior_evaluation}
                        </p>
                    </div>
                </motion.div>
            )}

            <div className="flex flex-col xl:flex-row gap-6">
                <div className="flex-1 bg-white rounded-3xl p-8 shadow-sm border border-[#2D2D2D]/5 flex flex-col h-[700px]">
                    <div className="flex items-center justify-between mb-8">
                        <div>
                            <h3 className="text-2xl font-bold tracking-tight">60-Day Master Plan</h3>
                            <p className="text-[#2D2D2D]/60 text-sm">Generated by Pawgress AI</p>
                        </div>
                        <div className="flex items-center gap-2">
                            <button
                                disabled={selectedDay === 1}
                                onClick={() => setSelectedDay(Math.max(1, selectedDay - 1))}
                                className="p-2 border border-[#2D2D2D]/10 rounded-full hover:bg-gray-50 transition-colors disabled:opacity-30"
                            >
                                <ChevronLeft size={18} />
                            </button>
                            <button
                                disabled={selectedDay === 60}
                                onClick={() => setSelectedDay(Math.min(60, selectedDay + 1))}
                                className="p-2 border border-[#2D2D2D]/10 rounded-full hover:bg-gray-50 transition-colors disabled:opacity-30"
                            >
                                <ChevronRight size={18} />
                            </button>
                        </div>
                    </div>

                    <div className="overflow-y-auto pr-2 pb-4 styled-scrollbar">
                        <div className="grid grid-cols-5 gap-3">
                            {Array.from({ length: 60 }).map((_, i) => {
                                const dayNum = i + 1;
                                const isSelected = selectedDay === dayNum;
                                const isPast = dayNum < selectedDay;

                                // Find the specific day data
                                const dayObj = safePlan.find((d: any) => d.day === dayNum)
                                const isRest = dayObj?.focus?.toLowerCase().includes('rest')

                                return (
                                    <button
                                        key={dayNum}
                                        onClick={() => setSelectedDay(dayNum)}
                                        className={`relative flex flex-col items-center justify-center p-4 rounded-2xl border-2 transition-all min-h-[100px]
                                        ${isSelected
                                                ? 'border-[#2D2D2D] bg-[#2D2D2D] text-white shadow-lg scale-105 z-10'
                                                : isPast
                                                    ? 'border-[#2D2D2D]/5 bg-gray-50 text-[#2D2D2D]/60 hover:border-[#2D2D2D]/20'
                                                    : 'border-[#2D2D2D]/10 bg-white text-[#2D2D2D] hover:border-[#2D2D2D]/30 shadow-sm'
                                            }
                                    `}
                                    >
                                        <span className="text-xs font-bold uppercase tracking-widest opacity-60 mb-1">Day</span>
                                        <span className={`text-2xl font-black ${isSelected ? 'text-white' : ''}`}>{dayNum}</span>

                                        {isPast && !isSelected && (
                                            <div className="absolute top-2 right-2 text-emerald-500">
                                                <CheckCircle2 size={14} />
                                            </div>
                                        )}
                                        {isRest && (
                                            <div className={`mt-2 w-10 h-1 rounded-full ${isSelected ? 'bg-white/30' : 'bg-blue-200'}`} />
                                        )}
                                        {!isRest && !isPast && !isSelected && (
                                            <div className="mt-2 w-10 h-1 rounded-full bg-amber-200" />
                                        )}
                                    </button>
                                )
                            })}
                        </div>
                    </div>
                </div>

                {/* Right Column - Day Details */}
                <div className="w-full xl:w-[400px] bg-[#FAF9F5] rounded-3xl p-8 shadow-sm border border-[#2D2D2D]/10 flex flex-col h-[700px] relative overflow-hidden">
                    <div className="absolute top-0 right-0 p-8 opacity-5">
                        <Target size={120} />
                    </div>

                    <AnimatePresence mode="wait">
                        <motion.div
                            key={selectedDay}
                            initial={{ opacity: 0, x: 20 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, x: -20 }}
                            transition={{ duration: 0.2 }}
                            className="relative z-10 flex flex-col h-full"
                        >
                            <div className="inline-flex items-center gap-2 px-3 py-1 bg-[#2D2D2D]/5 rounded-full text-xs font-bold text-[#2D2D2D]/60 w-fit mb-6">
                                <CalendarIcon size={14} /> Day {dayNumber} of 60
                            </div>

                            <h4 className="text-3xl font-black tracking-tight text-[#2D2D2D] mb-4 leading-none">
                                {currentDayData.focus}
                            </h4>

                            <p className="text-[#2D2D2D]/70 font-medium leading-relaxed mb-8">
                                {currentDayData.description || "No description provided for today."}
                            </p>

                            <div className="flex-1 overflow-y-auto pr-2 styled-scrollbar">
                                <h5 className="text-sm font-bold uppercase tracking-widest text-[#2D2D2D]/40 mb-4">Required Drills</h5>
                                <div className="space-y-3">
                                    {currentDayData.drills && currentDayData.drills.length > 0 ? (
                                        currentDayData.drills.map((drillName: string, idx: number) => {
                                            // find drill detail if exists
                                            const drillDetail = drillsSource.find((d: any) => d.name === drillName)
                                            return (
                                                <div key={idx} className="bg-white p-4 rounded-2xl border border-[#2D2D2D]/5 shadow-sm">
                                                    <div className="flex items-center justify-between mb-2">
                                                        <h6 className="font-bold text-[#2D2D2D] text-sm">{drillName}</h6>
                                                        <div className="text-xs bg-gray-100 px-2 py-1 rounded-md text-[#2D2D2D]/60 font-medium">
                                                            {drillDetail?.duration || "10 mins"}
                                                        </div>
                                                    </div>
                                                    <p className="text-xs text-[#2D2D2D]/60 leading-relaxed">
                                                        {drillDetail?.instructions || "Follow standard procedures for this drill."}
                                                    </p>
                                                </div>
                                            )
                                        })
                                    ) : (
                                        <div className="bg-white/50 border border-[#2D2D2D]/5 border-dashed rounded-2xl p-6 text-center">
                                            <p className="text-sm text-[#2D2D2D]/60 font-medium">Rest day! Enjoy some downtime.</p>
                                        </div>
                                    )}
                                </div>
                            </div>

                            <div className="mt-6 pt-4 border-t border-[#2D2D2D]/10">
                                <button className="w-full py-4 bg-[#2D2D2D] text-white rounded-xl font-bold flex items-center justify-center gap-2 shadow-lg hover:bg-black transition-all">
                                    <CheckCircle2 size={18} /> Mark Complete
                                </button>
                            </div>
                        </motion.div>
                    </AnimatePresence>
                </div>

                <style jsx global>{`
                    .styled-scrollbar::-webkit-scrollbar {
                        width: 6px;
                    }
                    .styled-scrollbar::-webkit-scrollbar-track {
                        background: transparent;
                    }
                    .styled-scrollbar::-webkit-scrollbar-thumb {
                        background-color: rgba(45, 45, 45, 0.1);
                        border-radius: 10px;
                    }
                    .styled-scrollbar::-webkit-scrollbar-thumb:hover {
                        background: rgba(0, 0, 0, 0.2);
                    }
                `}</style>
            </div>
        </div>
    )
}
